title: Thomas C. H. Lux
author: Thomas C. H. Lux
email: thomas.ch.lux@gmail.com
description: >
  I work towards useful Artificial Intelligence by developing
  mathematical theory, writing high performance software, and
  rigorously testing the accuracy and quality (of theory and code) in
  application. I frequent tools from approximation theory, numerical
  analysis, and nonparametric statistics.

theme: minima

minima:
  social_links:
    twitter: tchlux
    github: tchlux
    linkedin: thomas-ch-lux
    facebook: thomas.ch.lux

header_pages:
 - publications.md
 - resume.md


