name: Thomas C.H. Lux
description: >
    My personal website.
about: >
    This displays information about me.

master_repo: false
url: "https://tchlux.github.io"
markdown: kramdown
highlighter: rouge
subdomain_slug: nuthin
# make on_subdomain false if using on a root domain
on_subdomain: false


plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           thomas.ch.lux
  avatar:         "https://avatars1.githubusercontent.com/u/537678?s=240&v=4"
  email:          "tchlux@vt.edu"
  # Social networking links used in footer. Update and remove as you like.
  twitter: tchlux
  github: https://github.com/tchlux
  stackexchange: https://stackoverflow.com/users/6132097/thomas-lux
  linkedin: https://www.linkedin.com/in/thomas-ch-lux

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
