title: Thomas C.H. Lux
author: Thomas C.H. Lux
email: thomas.ch.lux@gmail.com
description: >
  I specialize in AI / ML research and engineering, writing high
  performance code, and developing mathematical theory.

theme: minima

minima:
  social_links:
    twitter: tchlux
    github: tchlux
    linkedin: thomas-ch-lux
    gscholar: wamfO3sAAAAJ
    stoverflow: "6132097/thomas-lux"
    # facebook: thomas.ch.lux

header_pages:
#  - publications.md
#  - resume.md

header_links:
 - title: "Publications"
   url: "#publications"
 - title: "Projects"
   url: "#projects"
 - title: "Education"
   url: "#education"
 - title: "Personal"
   url: "#personal"
 - title: "Resume"
   url: "https://tchlux.github.io/documents/tchlux-resume.pdf"

google_analytics: UA-152383948-1


projects:
  - id: "lux2020fmodpy"
    title: "`fmodpy` Automatic Fortran Wrapper for Python"
    authors: "**Thomas C.H. Lux**"
    venue: "Github"
    month: "June"
    year: "2017-present"
    code: "https://github.com/tchlux/fmodpy"

  - id: "lux2020sync"
    title: "`sync` Lightweight Shell Script for File Synchronization"
    authors: "**Thomas C.H. Lux**"
    venue: "Github"
    month: "Jan"
    year: "2020"
    code: "https://github.com/tchlux/sync"

  - id: "lux2019quantum"
    title: "`qaml` Quantum Annealing Math Library"
    authors: "**Thomas C.H. Lux**, Tyler H. Chang, Sai Sindhura Tipirneni"
    venue: "Github"
    month: "October"
    year: "2019"
    pdf: "https://tchlux.github.io/papers/tchlux-2019-QIP.pdf"
    code: "https://github.com/tchlux/qaml"

  - id: "lux2018mpca"
    title: "Metric Principle Component Analysis: On Identifying Important Subspaces for Approximation"
    authors: "**Thomas C.H. Lux**, Tyler H. Chang"
    venue: "Github"
    month: "December"
    year: "2018"
    pdf: "https://tchlux.github.io/papers/tchlux-2018-mpca.pdf"

  - id: "lux2017adversarial"
    title: "Adversarial Control of Neural Network Policies"
    authors: "**Thomas C.H. Lux**, Reid Bixler, Colin Shea-Blymyer"
    venue: "Github"
    month: "November"
    year: "2017"
    pdf: "https://tchlux.github.io/papers/tchlux-2017-adversarial.pdf"

  - id: "lux2017omp"
    title: "Optimizing OpenDwarf Applications for CPU and GPU Platforms"
    authors: "**Thomas C.H. Lux**, Kyle Tanous"
    venue: "Github"
    month: "May"
    year: "2017"
    pdf: "https://tchlux.github.io/papers/tchlux-2017-omp-acc.pdf"
  

publications:
  - id: "wang2020design"
    type: "paper"
    status: "submitted"
    title: "Design Strategies and Approximation Methods for High-Performance Computing Variability Management"
    authors: "Yueyao Wang, Li Xu, **Thomas C.H. Lux**, Tyler H. Chang, Layne T. Watson, Yili Hong"
    venue: "Journal of Quality Technology"
    month: "May"
    year: "2020"

  - id: "lux2020interpolation"
    type: "paper"
    status: "submitted"
    title: "Interpolation of Sparse High-Dimensional Data"
    authors: "**Thomas C.H. Lux**, Layne T. Watson, Tyler H. Chang, Yili Hong, Kirk Cameron"
    venue: "Numerical Algorithms, Springer Journal"
    month: "September"
    year: "2019"
    pdf: "https://tchlux.github.io/papers/tchlux-2019-NUMA.pdf"

  - id: ""
    type: "paper"
    status: "submitted"
    title: "Algorithm XXX: DELAUNAYSPARSE: Interpolation via a Sparse Subset of the Delaunay Triangulationin Medium to High Dimensions"
    authors: "Tyler H. Chang, Layne T. Watson, **Thomas C.H. Lux**, Ali R. Butt, Kirk W. Cameron, Yili Hong"
    venue: "ACM Transactions on Mathematical Software"
    month: "March"
    year: "2019"

  - id: ""
    type: "paper"
    status: "accepted"
    title: "Analytic Test Functions for Generalizable Evaluation of Convex Optimization Techniques"
    authors: "**Thomas C.H. Lux**, Tyler H. Chang"
    venue: "Institute of Electrical and Electronics Engineers Southeastcon"
    month: "January"
    year: "2020"
    pdf: "https://tchlux.github.io/papers/tchlux-2020-IEEESE-2.pdf"

  - id: "lux2020effective"
    type: "paper"
    status: "accepted"
    title: "Effective Nonparametric Distribution Modeling for Distribution Approximation Applications"
    authors: "**Thomas C.H. Lux**, Layne T. Watson, Tyler H. Chang, Li Xu, Yueyao Wang, Jon Bernard, Yili Hong, Kirk W. Cameron"
    venue: "Institute of Electrical and Electronics Engineers Southeastcon"
    month: "January"
    year: "2020"
    pdf: "https://tchlux.github.io/papers/tchlux-2020-IEEESE-1.pdf"

  - id: "lux2020algorithm"
    type: "paper"
    status: "published"
    title: "An Algorithm for Constructing Monotone Quintic Interpolating Splines"
    authors: "**Thomas C.H. Lux**, Layne T. Watson, Tyler H. Chang, Li Xu, Yueyao Wang, Yili Hong"
    venue: "Spring Simulation Multiconference, High Performance Computing Symposium"
    month: "February"
    year: "2020"
    pdf: "https://tchlux.github.io/papers/tchlux-2019-HPC-1.pdf"
    link: "https://dl.acm.org/doi/abs/10.5555/3408207.3408247"

  - id: "chang2020managing"
    type: "paper"
    status: "published"
    title: "Managing Computationally Expensive Blackbox Multiobjective Optimization Problems with libEnsemble"
    authors: "Tyler H. Chang, Jeffrey Larson, Layne T. Watson, **Thomas C.H. Lux**"
    venue: "Spring Simulation Multiconference, High Performance Computing Symposium"
    month: "February"
    year: "2020"
    link: "https://dl.acm.org/doi/abs/10.5555/3408207.3408245"

  - id: "xu2020modeling"
    type: "paper"
    status: "published"
    title: "Modeling I/O Performance Variability in High-Performance Computing Systems Using Mixture Distributions"
    authors: "Li Xu, Yueyao Wang, **Thomas C.H. Lux**, Tyler Chang, Bo Li, Kirk Cameron, Layne Watson, Jon Bernard"
    venue: "Journal of Parallel and Distributed Computing"
    month: "January"
    year: "2020"
    link: "https://authors.elsevier.com/c/1abkr2f6jz12nQ"

  - id: "lux2019sustainable"
    type: "paper"
    status: "published"
    title: "A Case Study on a Sustainable Framework for Ethically Aware Predictive Modeling"
    authors: "**Thomas C.H. Lux**, Stefan Nagy, Mohammed Almannaa, Sirui Yao, Reid Bixler"
    venue: "IEEE International Symposium on Technology and Society (ISTAS)"
    month: "December"
    year: "2019"
    pdf: "https://tchlux.github.io/papers/tchlux-2019-ISTAS.pdf"
    link: "https://ieeexplore.ieee.org/abstract/document/8937885"
    video: "https://www.youtube.com/watch?v=L0WA9pcMMUw"

  - id: "lux2019quantum"
    type: "paper"
    status: "published"
    title: "Least Squares Solutions to Polynomial Systems of Equations with Quantum Annealing"
    authors: "**Thomas C.H. Lux**, Tyler H. Chang, Sai Sindhura Tipirneni"
    venue: "Quantum Information Processing, Springer"
    month: "October"
    year: "2019"
    pdf: "https://tchlux.github.io/papers/tchlux-2019-QIP.pdf"
    link: "https://link.springer.com/article/10.1007%2Fs11128-019-2489-x"
    code: "https://github.com/tchlux/qaml"

  - id: "cameron2019moana"
    type: "paper"
    status: "published"
    title: "MOANA: Modeling and Analyzing I/O Variability in Parallel System Experimental Design"
    authors: "Kirk W. Cameron, Ali Anwar, Yue Cheng, Li Xu, Bo Li, Uday Ananth, Jon Bernard, Chandler Jearls, **Thomas C.H. Lux**, Yili Hong, Layne T. Watson, Ali R. Butt"
    venue: "IEEE Transactions on Parallel and Distributed Systems"
    month: "January"
    year: "2019"
    link: "https://ieeexplore.ieee.org/document/8631172"

  - id: "mehmood2018optimized"
    type: "paper"
    status: "published"
    title: "Optimized Drag Reduction and Wake Dynamics Associated with Rotational Oscillations of a Circular Cylinder"
    authors: "A. Mehmood, M.R. Hajj, I. Akhtar, M. Ghommem, L.T. Watson, **T.C.H. Lux**"
    venue: "Contemporary Engineering Sciences (Hikari | International Publishers)"
    month: "November"
    year: "2018"
    link: "http://www.m-hikari.com/ces/ces2018/ces97-100-2018/89519.html"

  - id: "xu2018prediction"
    type: "poster"
    status: "published"
    title: "Prediction for Distributional Outcomes in the Management of High-Performance Computing Input/Output (I/O) Variability"
    authors: "Li Xu, **Thomas C.H. Lux**, Tyler Chang, Bo Li, Yili Hong, Layne Watson, Kirk Cameron, Jon Bernard"
    venue: "Joint Statistical Meeting (American Statistical Association)"
    month: "July"
    year: "2018"
    link: "https://ww2.amstat.org/meetings/jsm/2018/onlineprogram/AbstractDetails.cfm?abstractid=330148"

  - id: "lux2018nonparametric"
    type: "paper"
    status: "published"
    title: "Nonparametric Distribution Models for Predicting and Managing Computational Performance Variability"
    authors: "**Thomas C.H. Lux**, Layne T. Watson, Tyler H. Chang, Jon Bernard, Bo Li, Xiaodong Yu, Li Xu, Godmar Back, Ali R. Butt, Kirk W. Cameron, Yili Hong, Danfeng Yao"
    venue: "Institute of Electrical and Electronics Engineers Southeastcon"
    month: "April"
    year: "2018"
    pdf: "https://tchlux.github.io/papers/tchlux-2018-IEEESE.pdf"
    link: "https://ieeexplore.ieee.org/document/8478814"

  - id: "chang2018computing"
    type: "paper"
    status: "published"
    title: "Computing the Umbrella Neighbourhood of a Vertex in the Delaunay Triangulation and a Single Voronoi Cell in Arbitrary Dimension"
    authors: "Tyler H. Chang, Layne T. Watson, **Thomas C.H. Lux**, Sharath Raghvendra, Bo Li, Li Xu, Ali R. Butt, Kirk W. Cameron, Yili Hong"
    venue: "Institute of Electrical and Electronics Engineers Southeastcon"
    month: "April"
    year: "2018"
    link: "https://ieeexplore.ieee.org/document/8479003"

  - id: "lux2018predictive"
    type: "paper"
    status: "published"
    title: "Predictive Modeling of I/O Characteristics in High Performance Computing Systems"
    authors: "**Thomas C.H. Lux**, Layne T. Watson, Tyler H. Chang, Jon Bernard, Bo Li, Li Xu, Godmar Back, Ali R. Butt, Kirk W. Cameron, Yili Hong"
    venue: "Spring Simulation Multiconference, High Performance Computing Symposium"
    month: "April"
    year: "2018"
    pdf: "https://tchlux.github.io/papers/tchlux-2018-HPC_SpringSim.pdf"
    link: "https://dl.acm.org/citation.cfm?id=3213077"

  - id: "chang2018predicting"
    type: "paper"
    status: "published"
    title: "Predicting System Performance by Interpolation Using a High-Dimensional Delaunay Triangulation"
    authors: "Tyler H. Chang, Layne T. Watson, **Thomas C.H. Lux**, Jon Bernard, Bo Li, Li Xu, Godmar Back, Ali R. Butt, Kirk W. Cameron, Yili Hong"
    venue: "Spring Simulation Multiconference, High Performance Computing Symposium"
    month: "April"
    year: "2018"
    link: "https://dl.acm.org/citation.cfm?id=3213071"

  - id: "lux2018novel"
    type: "paper"
    status: "published"
    title: "Novel Meshes for Multivariate Interpolation and Approximation"
    authors: "**Thomas C.H. Lux**, Layne T. Watson, Tyler H. Chang, Jon Bernard, Bo Li, Xiaodong Yu, Li Xu, Godmar Back, Ali R. Butt, Kirk W. Cameron, Danfeng Yao, Yili Hong"
    venue: "Association for Computing Machinery Southeast Conference"
    month: "March"
    year: "2018"
    pdf: "https://tchlux.github.io/papers/tchlux-2018-ACMSE.pdf"
    link: "https://dl.acm.org/citation.cfm?id=3190687"

  - id: "chang2018polynomial"
    type: "paper"
    status: "published"
    title: "A Polynomial Time Algorithm for Multivariate Interpolation in Arbitrary Dimension via the Delaunay Triangulation"
    authors: "Tyler H. Chang, Layne T. Watson, **Thomas C.H. Lux**, Bo Li, Li Xu, Ali R. Butt, Kirk W. Cameron, Yili Hong"
    venue: "Association for Computing Machinery Southeast Conference"
    month: "March"
    year: "2018"
    link: "https://dl.acm.org/citation.cfm?doid=3190645.3190680"

  - id: "back2018teaching"
    type: "abstract only"
    status: "published"
    title: "Teaching Variability in a Core Systems Course"
    authors: "Godmar Back, Lance Chao, Pratik Anand, **Thomas C.H. Lux**, Bo Li, Ali Butt, Kirk Cameron"
    venue: "Proceedings of the 49th ACM Technical Symposium on Computer Science Education (SIGCSE)"
    month: "February"
    year: "2018"
    link: "https://dl.acm.org/citation.cfm?id=3162275"

  - id: "lux2016convergence"
    type: "paper"
    status: "published"
    title: "Convergence Rate Evaluation of Derivative Free Optimization Techniques"
    authors: "**Thomas C.H. Lux**"
    venue: "International Workshop on Machine Learning, Optimization, and Big Data (MOD)"
    month: "September"
    year: "2016"
    pdf: "https://tchlux.github.io/papers/tchlux-2016-MOD.pdf"
    link: "https://link.springer.com/chapter/10.1007/978-3-319-51469-7_21"

  - id: "lux2016applications"
    type: "paper"
    status: "published"
    title: "Applications of Supervised Learning Techniques on Undergraduate Admissions Data"
    authors: "**Thomas C.H. Lux**, Randall Pittman, Maya Shende, Anil Shende"
    venue: "ACM International Conference on Computing Frontiers"
    month: "May"
    year: "2016"
    pdf: "https://tchlux.github.io/papers/tchlux-2016-ACM_Computing_Frontiers.pdf"
    link: "https://dl.acm.org/citation.cfm?id=2911717"

  - id: "example"
    type: "paper/poster/abstract/talk"
    status: "submitted/published"
    title: ""
    authors: ""
    venue: ""
    month: ""
    year: ""
    pdf: ""
    link: ""
    slides: ""
    doi: ""
